[tool.black]
line-length = 80

[tool.isort]
profile = "black"
line_length = 80
sections = ["FUTURE","STDLIB","D3B","FIRSTPARTY","THIRDPARTY","LOCALFOLDER"]
known_d3b = ["d3b_utils"]
known_kf = ["kf_utils","kf_lib_data_ingest"]